-- MySQL Script generated by MySQL Workbench
-- Tue 01 Nov 2022 06:23:04 PM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
-- SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
-- SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema maindb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema maindb
-- -----------------------------------------------------
-- CREATE SCHEMA IF NOT EXISTS `maindb` DEFAULT CHARACTER SET utf8 ;
DROP DATABASE IF EXISTS `maindb`;
CREATE DATABASE IF NOT EXISTS `maindb`;
USE `maindb` ;

-- -----------------------------------------------------
-- Table `Chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Chat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `host` VARCHAR(45) NOT NULL,
  `port` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `user_address` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_User_Address_idx` (`user_address` ASC) VISIBLE,
  CONSTRAINT `fk_User_Address`
    FOREIGN KEY (`user_address`)
    REFERENCES `Address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Chat_has_User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Chat_has_User` (
  `Chat_id` INT NOT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`Chat_id`, `User_id`),
  INDEX `fk_Chat_has_User_User1_idx` (`User_id` ASC) VISIBLE,
  INDEX `fk_Chat_has_User_Chat1_idx` (`Chat_id` ASC) VISIBLE,
  CONSTRAINT `fk_Chat_has_User_Chat1`
    FOREIGN KEY (`Chat_id`)
    REFERENCES `Chat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Chat_has_User_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(255) NOT NULL,
  `sent` TINYINT NOT NULL DEFAULT 0,
  `received` TINYINT NOT NULL DEFAULT 0,
  `error` VARCHAR(45) NULL,
  `in_chat` INT NOT NULL,
  `sent_by` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Message_Chat1_idx` (`in_chat` ASC) VISIBLE,
  INDEX `fk_Message_User1_idx` (`sent_by` ASC) VISIBLE,
  CONSTRAINT `fk_Message_Chat1`
    FOREIGN KEY (`in_chat`)
    REFERENCES `Chat` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Message_User1`
    FOREIGN KEY (`sent_by`)
    REFERENCES `User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- SET SQL_MODE=@OLD_SQL_MODE;
-- SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
-- SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
